server:
  port: 8080

spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: backend
  messages:
    basename: i18n/messages
    encoding: UTF-8
  profiles:
    active: @spring.profiles.active@

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      access: unrestricted
  metrics:
    tags:
      application: chatweb-backend

