server:
  port: 8080
  forward-headers-strategy: native

spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: backend
  messages:
    basename: i18n/messages
    encoding: UTF-8
  profiles:
    active: @spring.profiles.active@
  task:
    scheduling:
      pool:
        size: 4

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
    prometheus:
      access: unrestricted
  metrics:
    tags:
      application: chatweb-backend

