global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'chatweb_backend'
    metrics_path: '/actuator/prometheus'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    dns_sd_configs:
      - names:
          - 'cw_backend'
        type: 'A'
        port: 8443
